<?php
/**
 * Attrazioni "Cosa Vedere" per ogni destinazione del Lago di Garda.
 */
function ig_get_attrazioni() {
    return [

    'sirmione' => [
        ['name' => 'Castello Scaligero', 'excerpt' => 'Fortezza medievale del XIII secolo con ponte levatoio e darsena.', 'desc' => 'Il Castello Scaligero di Sirmione è una delle fortezze lacustri meglio conservate d\'Italia. Costruito tra il XIII e il XIV secolo dalla famiglia Della Scala, signori di Verona, il castello si erge maestoso all\'ingresso del borgo storico, circondato completamente dalle acque del lago. La sua darsena fortificata, unico esempio in Italia, proteggeva la flotta scaligera. Salendo le torri merlate si gode di una vista spettacolare a 360° sul lago, sui tetti del borgo e sulle montagne circostanti.'],
        ['name' => 'Grotte di Catullo', 'excerpt' => 'Resti di una grandiosa villa romana del I secolo d.C.', 'desc' => 'Le Grotte di Catullo sono i resti di una grande villa romana edificata tra la fine del I secolo a.C. e l\'inizio del I secolo d.C. sulla punta estrema della penisola di Sirmione. Con i suoi 2 ettari di estensione, è il più importante esempio di villa romana nell\'Italia settentrionale. Il sito archeologico comprende un museo che espone reperti trovati durante gli scavi, tra cui frammenti di affreschi, mosaici e oggetti di vita quotidiana.'],
        ['name' => 'Terme di Sirmione', 'excerpt' => 'Acque sulfuree a 69°C dal fondale del lago, famose per le proprietà curative.', 'desc' => 'Le Terme di Sirmione sono alimentate dall\'acqua sulfurea salsobromojodica che sgorga dalla sorgente Boiola, situata sul fondale del lago a 19 metri di profondità. L\'acqua emerge a una temperatura di 69°C ed è conosciuta fin dall\'antichità per le sue proprietà terapeutiche. I due stabilimenti termali — Catullo e Virgilio — offrono trattamenti per patologie otorinolaringoiatriche, dermatologiche e reumatiche, oltre a percorsi benessere e spa.'],
        ['name' => 'Jamaica Beach', 'excerpt' => 'Lastre di roccia piatta nelle acque cristalline, la spiaggia più iconica del Garda.', 'desc' => 'Jamaica Beach è una spiaggia libera situata sulla punta della penisola, vicino alle Grotte di Catullo. Le grandi lastre di roccia piatta si protendono nelle acque limpide e turchesi del lago, ricordando i paesaggi caraibici. In alcune zone l\'acqua termale calda si mescola con quella fredda del lago, creando un effetto termale naturale unico.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Vicoli medievali con botteghe, gelaterie e scorci romantici sul lago.', 'desc' => 'Il centro storico di Sirmione si sviluppa lungo la stretta penisola che si protende per quasi 4 chilometri nel Lago di Garda. Accessibile solo attraverso il ponte levatoio del Castello Scaligero, il borgo pedonale offre un\'atmosfera intima e romantica con botteghe artigiane, gelaterie storiche, enoteche e ristoranti con terrazza sul lago. Piazza Carducci è il cuore pulsante del paese.'],
        ['name' => 'Chiesa di San Pietro in Mavino', 'excerpt' => 'Chiesa longobarda dell\'VIII secolo con affreschi medievali tra gli ulivi.', 'desc' => 'La Chiesa di San Pietro in Mavino è uno degli edifici religiosi più antichi del Lago di Garda. Fondata nell\'VIII secolo dai Longobardi e ricostruita nel 1320, sorge sulla collina più alta della penisola immersa in un uliveto. L\'interno conserva preziosi affreschi del XII e XIII secolo con scene della vita di Cristo e dei santi.'],
        ['name' => 'Lido delle Bionde', 'excerpt' => 'Spiaggia attrezzata con acque turchesi e vista sulle montagne.', 'desc' => 'Il Lido delle Bionde è la spiaggia attrezzata più popolare di Sirmione, sulla sponda orientale della penisola. Le acque sono limpide e di un colore turchese intenso, con un fondale che degrada dolcemente — ideale per famiglie con bambini. La vista spazia sulle montagne della sponda veronese del lago.'],
    ],

    'desenzano-del-garda' => [
        ['name' => 'Castello di Desenzano', 'excerpt' => 'Fortezza medievale con vista panoramica sul basso lago.', 'desc' => 'Il Castello di Desenzano sorge sulla sommità della collina che domina il centro storico e il porto. Di origine tardo-antica, fu ampliato in epoca medievale e utilizzato come rifugio dalla popolazione durante le invasioni. Dalle sue mura si gode uno dei panorami più belli del basso Lago di Garda, spaziando da Sirmione a Peschiera fino alle colline moreniche.'],
        ['name' => 'Villa Romana', 'excerpt' => 'Mosaici policromi tra i più importanti del Nord Italia.', 'desc' => 'La Villa Romana di Desenzano è un complesso residenziale tardo-antico risalente al IV secolo d.C., situato a pochi passi dal lungolago. È celebre per i suoi straordinari mosaici pavimentali policromi, considerati tra i più importanti e meglio conservati dell\'Italia settentrionale. Le scene raffigurano episodi di caccia, allegorie e motivi geometrici di raffinata fattura.'],
        ['name' => 'Duomo di Santa Maria Maddalena', 'excerpt' => 'Chiesa rinascimentale con una pala di Andrea Celesti.', 'desc' => 'Il Duomo di Desenzano, dedicato a Santa Maria Maddalena, fu costruito nel XVI secolo su progetto dell\'architetto Giulio Todeschini. All\'interno custodisce opere d\'arte di grande valore, tra cui una pala d\'altare di Andrea Celesti e un\'Ultima Cena di Giambattista Tiepolo. La facciata neoclassica si affaccia sulla piazza principale del centro storico.'],
        ['name' => 'Porto Vecchio', 'excerpt' => 'Il cuore pulsante della vita sociale con locali e mercati.', 'desc' => 'Il Porto Vecchio di Desenzano è il punto di ritrovo più vivace della città, circondato da portici, caffè, ristoranti e negozi. Ogni martedì si tiene uno dei mercati più grandi del Lago di Garda, che attira visitatori da tutta la regione. La passeggiata lungo il porto offre scorci pittoreschi con le barche ormeggiate e le facciate colorate delle case.'],
        ['name' => 'Lungolago', 'excerpt' => 'Passeggiata panoramica dal porto fino alla spiaggia.', 'desc' => 'Il lungolago di Desenzano è una delle passeggiate più piacevoli del Garda. Si snoda dal Porto Vecchio fino alla Spiaggia d\'Oro, costeggiando giardini curati, sculture contemporanee e punti panoramici. Al tramonto, con il sole che si tuffa dietro le colline bresciane, diventa uno dei luoghi più romantici del lago.'],
        ['name' => 'Museo Archeologico Rambotti', 'excerpt' => 'Reperti dell\'età del Bronzo e il famoso aratro più antico d\'Europa.', 'desc' => 'Il Museo Civico Archeologico Giovanni Rambotti ospita una ricca collezione di reperti provenienti dalle palafitte preistoriche del lago, patrimonio UNESCO. Il pezzo più celebre è un aratro in legno risalente all\'età del Bronzo, considerato il più antico d\'Europa. Il museo racconta la vita quotidiana delle comunità lacustri che popolavano le rive del Garda millenni fa.'],
    ],

    'salo' => [
        ['name' => 'Duomo di Salò', 'excerpt' => 'Cattedrale gotico-rinascimentale con opere di Romanino e Moretto.', 'desc' => 'Il Duomo di Santa Maria Annunziata è il principale luogo di culto di Salò e uno dei più importanti del Lago di Garda. Costruito nel XV secolo in stile tardo-gotico, custodisce al suo interno capolavori di artisti bresciani come il Romanino, il Moretto e Paolo Veneziano. Il polittico ligneo dell\'altare maggiore è un\'opera di straordinaria bellezza e raffinatezza.'],
        ['name' => 'Lungolago di Salò', 'excerpt' => 'La passeggiata più lunga del Lago di Garda tra palazzi e giardini.', 'desc' => 'Il lungolago di Salò è considerato il più lungo e scenografico del Lago di Garda. Si snoda per oltre un chilometro costeggiando eleganti palazzi storici, boutique, caffè e giardini. La vista si apre sul golfo con le montagne sullo sfondo. È il luogo ideale per una passeggiata rilassante, un gelato al tramonto o semplicemente per ammirare la bellezza del paesaggio.'],
        ['name' => 'Palazzo della Magnifica Patria', 'excerpt' => 'Sede storica del governo della Riviera, oggi municipio.', 'desc' => 'Il Palazzo della Magnifica Patria, affacciato sul lungolago, fu per secoli la sede del Consiglio della Comunità di Riviera, l\'organismo che governava le 42 comunità della sponda occidentale del lago sotto la Repubblica di Venezia. L\'edificio rinascimentale, con la sua loggia e la torre dell\'orologio, è oggi sede del Comune e ospita il Museo del Nastro Azzurro.'],
        ['name' => 'MuSa - Museo di Salò', 'excerpt' => 'Museo moderno che racconta la storia della città e della RSI.', 'desc' => 'Il MuSa è il museo civico di Salò, ospitato nell\'ex convento di Santa Giustina. Il percorso espositivo racconta la storia della città dalle origini romane fino al periodo della Repubblica Sociale Italiana (1943-1945), quando Salò fu capitale della RSI. Il museo ospita anche mostre temporanee di arte contemporanea e una sezione dedicata alla musica con strumenti storici.'],
        ['name' => 'Isola del Garda', 'excerpt' => 'La più grande isola del lago con villa neogotica e giardini.', 'desc' => 'L\'Isola del Garda, situata nel golfo di Salò, è la più grande isola del Lago di Garda. Ospita una splendida villa in stile neogotico-veneziano costruita all\'inizio del Novecento, circondata da giardini all\'italiana con piante esotiche e mediterranee. L\'isola è visitabile da marzo a ottobre con tour guidati in barca che partono da Salò e da altri paesi del lago.'],
    ],

    'gardone-riviera' => [
        ['name' => 'Il Vittoriale degli Italiani', 'excerpt' => 'La dimora-museo di Gabriele d\'Annunzio, monumento nazionale.', 'desc' => 'Il Vittoriale degli Italiani è un complesso monumentale voluto dal poeta Gabriele d\'Annunzio tra il 1921 e il 1938 come memoria della sua vita e delle imprese degli italiani durante la Prima Guerra Mondiale. Si estende su 9 ettari e comprende la Prioria (la casa-museo), il teatro all\'aperto con 1.500 posti, la nave Puglia incastonata nella collina, i giardini e il mausoleo. È il monumento più visitato del Lago di Garda.'],
        ['name' => 'Giardino Botanico Hruska', 'excerpt' => 'Oltre 2.000 specie di piante tra cascate e sculture.', 'desc' => 'La Fondazione André Heller, conosciuta come Giardino Botanico Hruska, è un\'oasi botanica creata nel 1910 dal naturalista Arturo Hruska e successivamente arricchita dall\'artista multimediale André Heller. Su una superficie di 10.000 mq convivono oltre 2.000 specie vegetali provenienti da ogni continente, intervallate da installazioni artistiche contemporanee e attraversate da ruscelli e cascate.'],
        ['name' => 'Torre di San Marco', 'excerpt' => 'Torre panoramica medievale nel borgo storico.', 'desc' => 'La Torre di San Marco è uno dei simboli di Gardone Riviera. Di origine medievale, svetta sul borgo vecchio di Gardone di Sopra, un intrico di vicoli acciottolati, scalinate e case in pietra coperte di glicini. Dalla torre si gode una vista magnifica sul lago e sulle montagne circostanti. Il borgo intorno alla torre conserva intatto il fascino di un piccolo villaggio gardesano d\'altri tempi.'],
        ['name' => 'Lungolago e Grand Hotel', 'excerpt' => 'Elegante passeggiata tra ville liberty e hotel storici.', 'desc' => 'Il lungolago di Gardone Riviera è uno dei più eleganti del Garda, fiancheggiato da ville in stile liberty, giardini lussureggianti e hotel storici come il Grand Hotel, costruito nel 1884 e frequentato da teste coronate e celebrità. Il microclima mite favorisce la crescita di palme, limoni, oleandri e bougainvillea che donano al paesaggio un\'atmosfera quasi mediterranea.'],
        ['name' => 'Chiesa di San Nicolò', 'excerpt' => 'Parrocchiale del XVIII secolo con affreschi e vista lago.', 'desc' => 'La Chiesa parrocchiale di San Nicolò, situata nel cuore di Gardone di Sopra, risale al XVIII secolo ed è stata edificata sui resti di un edificio sacro più antico. L\'interno presenta decorazioni barocche, affreschi e un altare in marmi policromi. Il sagrato offre un punto panoramico privilegiato sul lago e sul Monte Baldo in lontananza.'],
    ],

    'gargnano' => [
        ['name' => 'Palazzo Feltrinelli', 'excerpt' => 'Villa neoclassica, sede della RSI e oggi campus universitario.', 'desc' => 'Palazzo Feltrinelli è un\'imponente villa neoclassica costruita nel 1898 dalla famiglia di industriali e editori Feltrinelli. Durante la Repubblica Sociale Italiana (1943-1945) fu la residenza di Benito Mussolini. Oggi è sede del campus gardesano dell\'Università degli Studi di Milano e ospita corsi e convegni internazionali. I giardini si affacciano direttamente sul lago.'],
        ['name' => 'Chiostro di San Francesco', 'excerpt' => 'Chiostro duecentesco con colonne in pietra e agrumi scolpiti.', 'desc' => 'Il Chiostro di San Francesco è un gioiello dell\'architettura romanica del XIII secolo. Le colonne e i capitelli in pietra locale presentano decorazioni uniche che raffigurano agrumi — limoni e arance — testimonianza dell\'importanza della coltivazione degli agrumi nella storia economica del paese. È uno dei chiostri meglio conservati della sponda bresciana del Garda.'],
        ['name' => 'Limonaia La Malora', 'excerpt' => 'Antica serra per la coltivazione dei limoni, visitabile.', 'desc' => 'La Limonaia La Malora è una delle poche limonaie storiche ancora esistenti sul Lago di Garda, risalente al XVIII secolo. Queste strutture a terrazza protette da grandi pilastri in pietra e vetrate permettevano la coltivazione dei limoni anche nei mesi invernali. La visita permette di scoprire questa tradizione secolare unica nel Nord Italia e di passeggiare tra piante di limoni, cedri e pompelmi.'],
        ['name' => 'Villa Bettoni', 'excerpt' => 'Sontuosa villa settecentesca con giardino all\'italiana.', 'desc' => 'Villa Bettoni è considerata la più bella villa del Lago di Garda. Costruita nel XVIII secolo per la nobile famiglia Bettoni, presenta una facciata imponente con scalinata monumentale che scende verso il lago. Il giardino all\'italiana è ornato da statue, fontane e siepi geometriche. Gli interni, riccamente affrescati, testimoniano lo splendore della vita aristocratica gardesana.'],
        ['name' => 'Porto e Lungolago', 'excerpt' => 'Pittoresco porticciolo di pescatori con atmosfera autentica.', 'desc' => 'Il porto di Gargnano conserva l\'atmosfera autentica di un borgo di pescatori. Le casette colorate si affacciano direttamente sull\'acqua, le barche dondolano nel porticciolo e i vicoli stretti conducono a piazzette nascoste. Gargnano è considerato uno dei paesi meno turistici e più genuini del Garda, amato da D.H. Lawrence che vi soggiornò e lo descrisse nei suoi scritti.'],
    ],

    'limone-sul-garda' => [
        ['name' => 'Limonaie del Castèl', 'excerpt' => 'Le storiche serre per limoni restaurate, oggi museo a cielo aperto.', 'desc' => 'Le Limonaie del Castèl sono la principale attrazione di Limone sul Garda, un sistema di serre terrazzate utilizzate dal XIII secolo per coltivare agrumi a queste latitudini. Restaurate e aperte al pubblico, permettono di passeggiare tra piante di limoni, cedri e aranci immersi in un paesaggio verticale di pilastri in pietra e terrazze affacciate sul lago. Un museo multimediale racconta la storia di questa tradizione unica.'],
        ['name' => 'Chiesa di San Rocco', 'excerpt' => 'Piccola chiesa panoramica del XVI secolo affacciata sul lago.', 'desc' => 'La Chiesa di San Rocco sorge in posizione elevata sopra il porto vecchio di Limone, raggiungibile tramite una scalinata in pietra. Costruita nel XVI secolo come ringraziamento per la fine di un\'epidemia di peste, offre dalla sua terrazza uno dei panorami più fotografati del Lago di Garda, con vista sulla costa rocciosa e sulle acque azzurre sottostanti.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Vicoli stretti e colorati tra il lago e la montagna.', 'desc' => 'Il centro storico di Limone si sviluppa in uno spazio stretto tra le pareti rocciose della montagna e le acque del lago. I vicoli pedonali sono un susseguirsi di scalinate, archi in pietra, facciate colorate con balconi fioriti e botteghe di prodotti locali — in particolare l\'olio extravergine di oliva del Garda e i limoncini. L\'atmosfera è pittoresca e raccolta, perfetta per perdersi senza fretta.'],
        ['name' => 'Pista Ciclabile del Garda', 'excerpt' => 'Spettacolare pista sospesa sull\'acqua, la più bella d\'Europa.', 'desc' => 'La pista ciclabile del Garda è un percorso mozzafiato scavato e sospeso sulla roccia a strapiombo sul lago, collegando Limone a Riva del Garda. Inaugurata nel 2018, è stata definita da molti la pista ciclabile più bella d\'Europa. Il tracciato attraversa gallerie illuminate, passerelle a sbalzo sull\'acqua e punti panoramici che offrono viste indimenticabili sul lago e sulle montagne.'],
        ['name' => 'Porto Vecchio', 'excerpt' => 'Porticciolo storico con barche colorate e ristorantini.', 'desc' => 'Il Porto Vecchio di Limone è un angolo di autentico fascino gardesano. Le barche dei pescatori dondolano nell\'acqua cristallina, circondati da piccoli ristoranti dove gustare pesce di lago fresco. La sera, le luci calde dei locali si riflettono sull\'acqua creando un\'atmosfera magica. Da qui partono anche i battelli del servizio di navigazione del lago verso gli altri paesi della costa.'],
    ],

    'tremosine-sul-garda' => [
        ['name' => 'Terrazza del Brivido', 'excerpt' => 'Balcone a strapiombo a 350 metri sopra il lago.', 'desc' => 'La Terrazza del Brivido è una piattaforma panoramica sospesa a 350 metri di altezza sopra le acque del Lago di Garda, situata presso l\'Hotel Paradiso di Pieve di Tremosine. La vista vertiginosa è stata definita da Winston Churchill come "l\'ottava meraviglia del mondo". La terrazza offre una prospettiva mozzafiato sul lago, sulla costa bresciana e sulle montagne del Trentino.'],
        ['name' => 'Strada della Forra', 'excerpt' => 'Strada panoramica scavata nella roccia, set di un film di James Bond.', 'desc' => 'La Strada della Forra è una strada spettacolare scavata nella gola del torrente Brasa che collega il lungolago al borgo di Pieve di Tremosine. Attraversa gallerie naturali, tornanti vertiginosi e strette forre con pareti di roccia alte decine di metri. La strada è stata usata come set per il film di James Bond "Quantum of Solace" (2008) e fu definita da Churchill come la strada più bella del mondo.'],
        ['name' => 'Pieve di Tremosine', 'excerpt' => 'Borgo medievale sull\'altopiano con vista mozzafiato.', 'desc' => 'Pieve è il centro principale di Tremosine, un borgo medievale arroccato sull\'altopiano a 414 metri sul livello del lago. La piazzetta centrale, la chiesa parrocchiale e i vicoli in pietra conservano un\'atmosfera d\'altri tempi. Dalla balaustra del paese si gode una vista panoramica straordinaria sul Lago di Garda, che si estende fino alla penisola di Sirmione a sud.'],
        ['name' => 'Parco Avventura Busatte', 'excerpt' => 'Sentieri e percorsi avventura con scalinate panoramiche.', 'desc' => 'Il Parco delle Busatte-Tempesta offre uno dei sentieri escursionistici più scenografici del Lago di Garda. Il percorso include oltre 400 gradini di scale metalliche ancorate alla parete rocciosa a picco sul lago, regalando panorami da togliere il fiato. Ideale per famiglie e amanti del trekking, il parco si snoda tra boschi di lecci e affacci spettacolari sulla costa.'],
        ['name' => 'Altopiano di Tremosine', 'excerpt' => 'Prati alpini, malghe e sentieri tra 18 frazioni panoramiche.', 'desc' => 'L\'altopiano di Tremosine è un vasto territorio che comprende 18 piccole frazioni sparse tra prati verdi, boschi e malghe a quote comprese tra 400 e 1.900 metri. È il luogo ideale per escursioni a piedi, in mountain bike o a cavallo, con sentieri che offrono viste sempre diverse sul lago sottostante. Le malghe producono formaggi locali e offrono piatti della tradizione gardesana.'],
    ],

    'manerba-del-garda' => [
        ['name' => 'Rocca di Manerba', 'excerpt' => 'Parco archeologico e naturalistico con vista a 360° sul lago.', 'desc' => 'La Rocca di Manerba è un promontorio roccioso che si eleva per 216 metri sul livello del lago, dominando il paesaggio della sponda bresciana. Il parco archeologico-naturalistico che lo circonda conserva i resti di un castello medievale e testimonianze di insediamenti dall\'età del Bronzo. Dalla cima si gode una vista a 360° sul Lago di Garda, sull\'Isola del Garda e sulla penisola di Sirmione.'],
        ['name' => 'Isola San Biagio', 'excerpt' => 'Piccola isola raggiungibile a piedi con acque basse cristalline.', 'desc' => 'L\'Isola San Biagio, detta anche Isola dei Conigli, è una piccola isola situata di fronte a Manerba che, quando il livello del lago è basso, diventa raggiungibile a piedi attraverso un istmo sabbioso. Questo fenomeno naturale la rende un\'attrazione unica. L\'isola offre una spiaggia tranquilla immersa nella natura, con acque cristalline e una vegetazione lussureggiante.'],
        ['name' => 'Spiagge e Baia delle Sirene', 'excerpt' => 'Calette nascoste tra le più belle del Lago di Garda.', 'desc' => 'Il litorale di Manerba comprende alcune delle spiagge più belle e selvagge del Lago di Garda. La Baia delle Sirene, ai piedi della Rocca, è una caletta riparata con acque turchesi trasparenti. Le spiagge di Pisenze, Dusano e Porto Torchio offrono tratti sia liberi che attrezzati, circondati da ulivi e vegetazione mediterranea.'],
        ['name' => 'Museo Civico Archeologico', 'excerpt' => 'Reperti dalle palafitte preistoriche, patrimonio UNESCO.', 'desc' => 'Il Museo Civico Archeologico della Valtenesi, situato presso la Rocca di Manerba, raccoglie reperti provenienti dagli scavi delle palafitte preistoriche del lago — sito patrimonio UNESCO — e dalle diverse aree archeologiche del territorio. La collezione comprende ceramiche, utensili in selce e bronzo, e oggetti di vita quotidiana che raccontano millenni di storia gardesana.'],
    ],

    'peschiera-del-garda' => [
        ['name' => 'Fortezza di Peschiera', 'excerpt' => 'Fortezza veneziana patrimonio UNESCO a pianta pentagonale.', 'desc' => 'La Fortezza di Peschiera del Garda è un capolavoro di architettura militare realizzato dalla Repubblica di Venezia nel XVI secolo. La sua pianta a stella pentagonale perfetta, circondata completamente dalle acque del fiume Mincio, è stata inserita nel Patrimonio UNESCO nel 2017. Le possenti mura racchiudono il centro storico e offrono una passeggiata panoramica lungo i bastioni con vista sul lago e sulle montagne.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Borgo fortificato su un\'isola tra i canali del Mincio.', 'desc' => 'Il centro storico di Peschiera sorge su un\'isola naturale alla confluenza del fiume Mincio con il Lago di Garda. Circondato da mura veneziane e attraversato da canali, il borgo offre un\'esperienza unica: passeggiare tra piazze animate, ponti in pietra, ristorantini e negozi artigianali, con l\'acqua sempre presente come elemento dominante del paesaggio urbano.'],
        ['name' => 'Porta Brescia e Porta Verona', 'excerpt' => 'Le porte monumentali d\'ingresso alla città murata.', 'desc' => 'Le due porte monumentali — Porta Brescia a ovest e Porta Verona a est — sono gli accessi principali alla città fortificata di Peschiera. Costruite durante la dominazione veneziana e successivamente rafforzate dagli Asburgo, sono imponenti strutture in pietra con ponti levatoi, stemmi araldici e gallerie che attraversano le mura. Rappresentano un perfetto esempio di ingegneria militare rinascimentale.'],
        ['name' => 'Lungolago e Spiagge', 'excerpt' => 'Passeggiate panoramiche e spiagge sabbiose per famiglie.', 'desc' => 'Peschiera offre un ampio lungolago che si estende dalla fortezza verso sud, costeggiando spiagge sabbiose e parchi ombreggiati. La Spiaggia Cappuccini e la Spiaggia Lido sono perfette per famiglie grazie al fondale basso e sabbioso. Il percorso ciclabile lungo il Mincio parte da qui e conduce fino a Mantova attraverso le colline moreniche.'],
        ['name' => 'Santuario della Madonna del Frassino', 'excerpt' => 'Chiesa rinascimentale con chiostro e opere d\'arte.', 'desc' => 'Il Santuario della Madonna del Frassino, situato appena fuori dal centro, fu edificato nel 1511 dopo un\'apparizione mariana. L\'interno è riccamente decorato con opere di Paolo Farinati, Zenone Veronese e altri artisti veneti. Il chiostro del convento francescano annesso è un luogo di pace e raccoglimento, con un piccolo giardino curato dai frati.'],
    ],

    'lazise' => [
        ['name' => 'Castello Scaligero', 'excerpt' => 'Imponente castello medievale con torri e mura merlate.', 'desc' => 'Il Castello Scaligero di Lazise fu costruito nel IX secolo e rafforzato nel XIV secolo dalla famiglia Della Scala. Con le sue sei torri e le mura merlate che circondano il borgo, è uno dei castelli più scenografici del Lago di Garda. Il castello è proprietà privata, ma le mura esterne e la passeggiata lungo la cinta muraria sono accessibili e offrono scorci suggestivi.'],
        ['name' => 'Porto Vecchio', 'excerpt' => 'Porticciolo veneziano con la Dogana Veneta del XIV secolo.', 'desc' => 'Il Porto Vecchio di Lazise è un piccolo bacino circondato da edifici storici, tra cui la celebre Dogana Veneta (XIV secolo), che fu il primo edificio doganale della Repubblica di Venezia sul lago. Oggi la Dogana ospita eventi culturali e mostre. Il porto, con le sue barche colorate e i caffè all\'aperto, è il cuore della vita sociale del paese.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Primo comune libero d\'Italia con vicoli e piazze medievali.', 'desc' => 'Il centro storico di Lazise vanta un primato storico: nel 983 l\'imperatore Ottone II le concesse il privilegio di darsi un proprio statuto, rendendola di fatto il primo comune libero d\'Italia. I vicoli medievali, le piazzette con fontane, le botteghe artigiane e i ristoranti creano un\'atmosfera incantevole. La cinta muraria scaligera è quasi completamente conservata.'],
        ['name' => 'Chiesa di San Nicolò', 'excerpt' => 'Chiesa romanica del XII secolo con affreschi medievali.', 'desc' => 'La Chiesa di San Nicolò, situata nei pressi del porto, è un pregevole esempio di architettura romanica del XII secolo. L\'interno conserva frammenti di affreschi medievali che testimoniano la devozione dei marinai e dei pescatori che la frequentavano. La facciata in pietra e il piccolo campanile si inseriscono armoniosamente nel tessuto urbano del borgo antico.'],
        ['name' => 'Lungolago e Spiagge', 'excerpt' => 'Passeggiata tra i parchi e le spiagge della baia.', 'desc' => 'Il lungolago di Lazise offre una piacevole passeggiata tra parchi ombreggiati da cipressi e oleandri, con spiagge sia libere che attrezzate. La Baia di Lazise è una delle zone balneari più apprezzate della sponda veronese, con acque calme e pulite. Il panorama spazia dal Monte Baldo alle colline della sponda bresciana.'],
    ],

    'bardolino' => [
        ['name' => 'Chiesa di San Severo', 'excerpt' => 'Gioiello romanico del IX secolo con affreschi carolingi.', 'desc' => 'La Chiesa di San Severo è uno dei monumenti romanici più importanti della zona del Lago di Garda. Risalente al IX secolo, conserva al suo interno preziosi affreschi di epoca carolingia e romanica che rappresentano scene del Nuovo Testamento. La struttura architettonica, con le sue tre navate e l\'abside semicircolare, è un esempio perfetto di architettura religiosa altomedievale.'],
        ['name' => 'Museo del Vino', 'excerpt' => 'La storia della viticoltura gardesana nella cantina Zeni.', 'desc' => 'Il Museo del Vino, ospitato nella storica Cantina Zeni, racconta la tradizione vitivinicola di Bardolino e del Lago di Garda attraverso attrezzi antichi, botti storiche e pannelli informativi. Il percorso si conclude con una degustazione dei vini locali — il Bardolino, il Chiaretto e il Custoza — accompagnati dall\'olio extravergine del Garda. L\'ingresso è gratuito.'],
        ['name' => 'Museo dell\'Olio d\'Oliva', 'excerpt' => 'Frantoio storico che racconta la produzione dell\'olio gardesano.', 'desc' => 'Il Museo dell\'Olio d\'Oliva, situato nel frantoio Cisano, documenta la storia millenaria della produzione olearia sul Lago di Garda. Attraverso macchinari originali, pannelli didattici e una raccolta di attrezzi storici, il visitatore scopre ogni fase della lavorazione delle olive. Il museo offre degustazioni dell\'olio extravergine DOP Garda che si produce sulle colline circostanti.'],
        ['name' => 'Lungolago e Porto', 'excerpt' => 'Passeggiata vivace con locali, gelaterie e mercatini.', 'desc' => 'Il lungolago di Bardolino è una delle passeggiate più animate del Garda, fiancheggiata da locali, gelaterie, ristoranti e negozi. Il porto turistico ospita barche a vela e motoscafi, ed è punto di partenza per gite in battello. In autunno, Bardolino si anima con la Festa dell\'Uva e del Vino e la Festa del Chiaretto, eventi enogastronomici che attirano migliaia di visitatori.'],
        ['name' => 'Punta Cornicello', 'excerpt' => 'Promontorio panoramico tra due spiagge con vista aperta sul lago.', 'desc' => 'Punta Cornicello è un piccolo promontorio che separa le due principali spiagge di Bardolino, offrendo una vista aperta e panoramica sul Lago di Garda. È un punto ideale per ammirare tramonti spettacolari con il sole che scende dietro il Monte Baldo e la costa bresciana. Un breve sentiero tra gli ulivi conduce alla punta, dove una panchina invita alla contemplazione.'],
    ],

    'malcesine' => [
        ['name' => 'Castello Scaligero', 'excerpt' => 'Castello a strapiombo sul lago con il museo di Goethe.', 'desc' => 'Il Castello Scaligero di Malcesine è arroccato su uno sperone roccioso a picco sul lago, dominando il borgo e il porto. Ospita il Museo di Storia Naturale del Garda e del Monte Baldo, e una sala dedicata a Goethe che nel 1786 fu arrestato mentre disegnava il castello, sospettato di essere una spia. Dalla torre si gode una vista panoramica straordinaria sul lago e sul Monte Baldo.'],
        ['name' => 'Funivia del Monte Baldo', 'excerpt' => 'Cabina rotante che sale a 1.760 m con vista a 360°.', 'desc' => 'La funivia Malcesine-Monte Baldo è una delle attrazioni più spettacolari del Lago di Garda. Le cabine rotanti a 360° salgono da Malcesine (90 m) fino a quota 1.760 m in circa 10 minuti, regalando un panorama mozzafiato sul lago, sulle Dolomiti e sulla Pianura Padana. In cima si aprono prati fioriti ideali per trekking in estate e sci in inverno. È anche uno dei punti di lancio per il parapendio più famosi d\'Europa.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Vicoli medievali con il Palazzo dei Capitani e il porto.', 'desc' => 'Il centro storico di Malcesine è un dedalo di vicoli medievali che scendono dal castello fino al porto. Il Palazzo dei Capitani del Lago, affacciato sull\'acqua, fu sede dei governatori veneziani ed è oggi un luogo per eventi e mostre. Le botteghe artigiane, i ristoranti con terrazza sul lago e le piazzette nascoste rendono ogni passeggiata una scoperta.'],
        ['name' => 'Porto Vecchio', 'excerpt' => 'Porticciolo pittoresco con barche colorate ai piedi del castello.', 'desc' => 'Il Porto Vecchio di Malcesine è uno dei luoghi più fotografati del Lago di Garda. Le barche dei pescatori dondolano ai piedi del castello scaligero, circondati da casette colorate con persiane verdi. I ristoranti sul porto servono pesce di lago fresco con vista spettacolare. Goethe lo descrisse come un luogo di meravigliosa bellezza nel suo "Viaggio in Italia".'],
        ['name' => 'Val di Sogno', 'excerpt' => 'Baia romantica con acque cristalline e vista sull\'Isola dell\'Olivo.', 'desc' => 'La Val di Sogno è una piccola baia situata a sud di Malcesine, considerata uno dei luoghi più romantici del Lago di Garda. Le acque cristalline, la spiaggia di ciottoli e la vista sull\'Isola dell\'Olivo (o Isola del Sogno) creano uno scenario da cartolina. Il nome stesso, "Valle del Sogno", evoca la magia di questo angolo nascosto, perfetto per un bagno al tramonto.'],
    ],

    'brenzone-sul-garda' => [
        ['name' => 'Castelletto di Brenzone', 'excerpt' => 'Borgo medievale sospeso sulla scogliera con vicoli in pietra.', 'desc' => 'Castelletto è una delle frazioni più suggestive di Brenzone, un borgo medievale arroccato sulla scogliera a picco sul lago. I vicoli stretti in pietra, gli archi, le scalinate e le case con i tetti in coppi creano un\'atmosfera sospesa nel tempo. Il borgo è pedonale e offre scorci panoramici inaspettati sull\'acqua turchese sottostante.'],
        ['name' => 'Chiesa di San Zeno de l\'Oselet', 'excerpt' => 'Chiesetta romanica isolata raggiungibile solo a piedi.', 'desc' => 'La Chiesa di San Zeno de l\'Oselet è un piccolo gioiello romanico dell\'XI secolo, situata in posizione isolata sulle pendici del Monte Baldo, raggiungibile solo con un\'escursione a piedi. Gli affreschi medievali interni sono sorprendentemente ben conservati. Il sentiero che conduce alla chiesa attraversa uliveti e boschi di lecci, offrendo viste panoramiche sul lago.'],
        ['name' => 'Passeggiata lungolago', 'excerpt' => 'Sentiero costiero che collega le frazioni tra ulivi e spiagge.', 'desc' => 'La passeggiata lungolago di Brenzone collega le diverse frazioni del comune — da Magugnano a Castelletto — attraverso un sentiero costiero che si snoda tra uliveti secolari, piccole spiagge di ciottoli e porticcioli di pescatori. Il percorso, lungo circa 3 km, è pianeggiante e adatto a tutti, con numerose panchine e punti panoramici per soste contemplative.'],
        ['name' => 'Monte Baldo versante ovest', 'excerpt' => 'Sentieri escursionistici con flora alpina e viste sul lago.', 'desc' => 'Il versante occidentale del Monte Baldo che sovrasta Brenzone offre una rete di sentieri escursionistici di varia difficoltà immersi in una natura straordinaria. Il Monte Baldo è conosciuto come il "Giardino d\'Europa" per la sua eccezionale biodiversità botanica. I sentieri conducono attraverso boschi, prati fioriti e pascoli alpini, con panorami sempre più ampi sul lago sottostante.'],
        ['name' => 'Porto di Brenzone', 'excerpt' => 'Piccolo porto di pescatori con atmosfera autentica e tranquilla.', 'desc' => 'Il porto di Brenzone è un minuscolo approdo che conserva l\'anima più autentica della vita lacustre. Le reti dei pescatori stese ad asciugare, le barche in legno e i gatti che sonnecchiano al sole creano un quadro di vita quotidiana lontano dal turismo di massa. Qui si può ancora assistere alla partenza dei pescatori all\'alba e acquistare pesce fresco del lago.'],
    ],

    'riva-del-garda' => [
        ['name' => 'Torre Apponale', 'excerpt' => 'Torre civica del XIII secolo nel cuore della piazza principale.', 'desc' => 'La Torre Apponale, alta 34 metri, domina Piazza III Novembre, il salotto di Riva del Garda. Costruita nel XIII secolo come torre di avvistamento e di difesa del porto, oggi è aperta ai visitatori che possono salire i 165 gradini fino alla cima per godere di un panorama straordinario sull\'alto lago, sulle montagne circostanti e sul centro storico sottostante.'],
        ['name' => 'MAG - Museo Alto Garda', 'excerpt' => 'Museo nella Rocca con pinacoteca e mostre temporanee.', 'desc' => 'Il MAG Museo Alto Garda è ospitato nella Rocca di Riva, una fortezza medievale circondatada da un fossato nel centro della città. Il museo comprende una pinacoteca con opere dal XV al XX secolo, una sezione archeologica e spazi per importanti mostre temporanee di arte contemporanea. La Rocca stessa, con le sue torri e il ponte levatoio, è un monumento storico di grande fascino.'],
        ['name' => 'Cascata del Varone', 'excerpt' => 'Cascata alta 100 metri in una grotta naturale.', 'desc' => 'La Cascata del Varone è uno spettacolo naturale formato dal torrente Magnone che precipita per quasi 100 metri in una forra scavata nella roccia. Il parco, aperto dal 1874, è uno dei più antichi siti turistici del Trentino. Due passerelle panoramiche — una alla base e una a metà altezza — permettono di ammirare la potenza dell\'acqua e sentirne la forza. Un\'esperienza sensoriale unica.'],
        ['name' => 'Spiaggia degli Olivi', 'excerpt' => 'Grande spiaggia attrezzata con vista sulle montagne.', 'desc' => 'La Spiaggia degli Olivi è il lido principale di Riva del Garda, un\'ampia distesa di prato e ghiaia affacciata sull\'azzurro intenso dell\'alto lago. Attrezzata con lettini, bar e aree sportive, è il punto di ritrovo estivo per abitanti e turisti. Il vento termico "Ora del Garda" che soffia regolare nel pomeriggio la rende anche un paradiso per velisti e windsurfisti.'],
        ['name' => 'Bastione Veneziano', 'excerpt' => 'Fortezza panoramica raggiungibile a piedi sopra la città.', 'desc' => 'Il Bastione è una fortezza veneziana del XVI secolo arroccata a 200 metri di altezza sopra Riva del Garda. Raggiungibile con una breve escursione dal centro (circa 20 minuti), offre dalla sua terrazza una delle viste più spettacolari dell\'intero Lago di Garda: l\'alto lago stretto tra le montagne, con Riva e Torbole ai suoi piedi. Al tramonto il panorama diventa indimenticabile.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Piazze eleganti, portici e atmosfera mitteleuropea.', 'desc' => 'Il centro storico di Riva del Garda riflette la sua storia asburgica con piazze eleganti, palazzi signorili, portici commerciali e un\'atmosfera che mescola influenze italiane e mitteleuropee. Piazza III Novembre, affacciata sul porto e dominata dalla Torre Apponale, è il cuore della vita sociale. I caffè sotto i portici, le librerie e le botteghe artigiane rendono piacevole ogni passeggiata.'],
    ],

    'torbole' => [
        ['name' => 'Porto Vecchio e Dogana Veneta', 'excerpt' => 'Porticciolo storico dove Goethe descrisse il lago come un miracolo.', 'desc' => 'Il Porto Vecchio di Torbole è un luogo carico di storia e fascino. Qui nel 1786 Johann Wolfgang von Goethe fece il suo primo incontro con il Lago di Garda, descrivendolo nel "Viaggio in Italia" come un miracolo della natura. La vecchia Dogana Veneta, affacciata sul porto, ricorda i tempi in cui Torbole era il confine tra i domini veneziani e quelli asburgici.'],
        ['name' => 'Spiagge per Windsurf e Kitesurf', 'excerpt' => 'Spot leggendario per gli sport del vento, tra i migliori al mondo.', 'desc' => 'Torbole è conosciuta in tutto il mondo come la capitale degli sport a vela del Lago di Garda. Il Peler, vento del mattino da nord, e l\'Ora, vento del pomeriggio da sud, creano condizioni ideali e costanti per windsurf, kitesurf e vela. Le spiagge di Torbole ospitano scuole, noleggi e competizioni internazionali che attirano sportivi da ogni parte d\'Europa.'],
        ['name' => 'Sentiero del Ponale', 'excerpt' => 'Antica strada militare scavata nella roccia con vista mozzafiato.', 'desc' => 'Il Sentiero del Ponale è una delle escursioni più famose del Trentino. Ricavato da un\'antica strada militare asburgica del 1851 scavata nella roccia a strapiombo sul lago, il percorso collega Riva del Garda al Lago di Ledro. Lungo circa 5 km, attraversa gallerie, tornanti panoramici e terrazze naturali che offrono viste vertiginose sull\'alto lago e sulle montagne circostanti.'],
        ['name' => 'Monte Brione', 'excerpt' => 'Collina tra Riva e Torbole con forti austro-ungarici e flora rara.', 'desc' => 'Il Monte Brione è una collina di 376 metri che separa Riva del Garda da Torbole. Sulla sua sommità si trovano i resti di un forte austro-ungarico e una serie di sentieri che attraversano un\'area di grande interesse botanico con specie mediterranee rare a queste latitudini. La passeggiata sulla cresta del Brione offre viste panoramiche su entrambi i versanti del lago.'],
        ['name' => 'Lungolago', 'excerpt' => 'Passeggiata colorata tra barche, vele e montagne.', 'desc' => 'Il lungolago di Torbole è un\'esplosione di colori: le vele colorate dei windsurf, le montagne che si specchiano nell\'acqua, le facciate dei palazzi veneziani e il verde degli ulivi. La passeggiata costeggia caffè all\'aperto, noleggi di attrezzature nautiche e piccole spiagge, con il Monte Baldo come sfondo costante. L\'atmosfera è sportiva e internazionale.'],
    ],

    'arco' => [
        ['name' => 'Castello di Arco', 'excerpt' => 'Ruderi medievali su uno sperone roccioso con affreschi trecenteschi.', 'desc' => 'Il Castello di Arco domina la città da uno sperone roccioso alto 273 metri, visibile da gran parte dell\'alto Garda. I ruderi della fortezza medievale, appartenuta ai Conti d\'Arco, includono la Torre Grande e una sala con affreschi trecenteschi raffiguranti un gioco di corte. La salita al castello attraversa un oliveto e regala panorami sempre più ampi sulla valle del Sarca e sul lago in lontananza.'],
        ['name' => 'Arboreto di Arco', 'excerpt' => 'Parco asburgico con piante esotiche e villa dell\'Arciduca.', 'desc' => 'L\'Arboreto di Arco fu creato a metà del XIX secolo dall\'Arciduca Alberto d\'Asburgo, che scelse Arco come residenza invernale grazie al suo microclima mite. Il parco ospita oltre 150 specie di piante esotiche — sequoie, palme, cedri del Libano — che prosperano in questo angolo di Trentino dal clima mediterraneo. La villa dell\'Arciduca e il parco circostante sono un\'oasi di pace e bellezza.'],
        ['name' => 'Climbing Crag', 'excerpt' => 'Capitale mondiale dell\'arrampicata con falesie per ogni livello.', 'desc' => 'Arco è universalmente riconosciuta come una delle capitali mondiali dell\'arrampicata sportiva. Le falesie calcaree che circondano la città offrono migliaia di vie di arrampicata per tutti i livelli, dalle pareti per principianti alle sfide estreme. Ogni anno Arco ospita il Rock Master, una delle competizioni di arrampicata più prestigiose al mondo, e attira climber da ogni continente.'],
        ['name' => 'Collegiata dell\'Assunta', 'excerpt' => 'Chiesa barocca con opere d\'arte e organo storico.', 'desc' => 'La Collegiata dell\'Assunta è il principale luogo di culto di Arco, una chiesa barocca del XVII secolo che sorge nel cuore del centro storico. L\'interno è decorato con stucchi, affreschi e pale d\'altare di pregevole fattura. L\'organo storico è uno dei più importanti del Trentino. La piazza antistante è il centro della vita sociale della città.'],
        ['name' => 'Centro Storico e Piazza III Novembre', 'excerpt' => 'Elegante centro con palazzi nobiliari e atmosfera asburgica.', 'desc' => 'Il centro storico di Arco conserva l\'eleganza della sua epoca asburgica, quando la città era rinomato luogo di villeggiatura della nobiltà mitteleuropea. Palazzi nobiliari, ville con giardini, portici e piazzette si susseguono in un tessuto urbano curato e piacevole. Il mercato settimanale del mercoledì e i numerosi caffè rendono il centro sempre vivace e accogliente.'],
    ],

    'toscolano-maderno' => [
        ['name' => 'Valle delle Cartiere', 'excerpt' => 'Museo industriale nella valle dove si produceva carta dal XIV secolo.', 'desc' => 'La Valle delle Cartiere è un sito di archeologia industriale unico in Europa. Dal XIV al XX secolo, lungo il torrente Toscolano, operavano decine di cartiere che producevano carta pregiata esportata in tutto il mondo. Oggi il Museo della Carta racconta questa tradizione secolare attraverso macchinari originali, documenti e dimostrazioni pratiche. Il sentiero lungo la valle è immerso in una natura rigogliosa.'],
        ['name' => 'Santuario di Supina', 'excerpt' => 'Chiesa cinquecentesca incastonata nella roccia a strapiombo.', 'desc' => 'Il Santuario della Madonna di Supina è un luogo di culto suggestivo costruito nel XVI secolo su una parete rocciosa a strapiombo sulla Valle delle Cartiere. La chiesa, raggiungibile attraverso un sentiero panoramico, è incastonata nella roccia e offre una vista vertiginosa sulla valle sottostante. L\'interno conserva ex-voto e testimonianze di fede popolare secolare.'],
        ['name' => 'Basilica di Sant\'Andrea', 'excerpt' => 'Chiesa romanica del XII secolo con cripta e capitelli scolpiti.', 'desc' => 'La Basilica di Sant\'Andrea a Maderno è uno dei più importanti edifici romanici del Lago di Garda. Risalente al XII secolo, presenta una facciata ornata con lesene, archetti e un rosone, mentre l\'interno conserva una cripta con capitelli scolpiti di epoca longobarda. Le colonne e i capitelli della navata sono un esempio pregevole di scultura romanica lombarda.'],
        ['name' => 'Lungolago e Porto', 'excerpt' => 'Passeggiata tra Toscolano e Maderno con ville e giardini.', 'desc' => 'Il lungolago che collega Toscolano a Maderno è una passeggiata piacevole tra ville storiche, giardini con piante esotiche e scorci panoramici sul lago. Il porto di Maderno è punto di partenza per i traghetti verso la sponda veronese. L\'atmosfera è tranquilla e rilassata, lontana dal turismo di massa, con piccole spiagge e ristoranti che servono specialità di pesce del lago.'],
        ['name' => 'Palazzo del Serraglio', 'excerpt' => 'Villa rinascimentale della famiglia Gonzaga con giardino storico.', 'desc' => 'Il Palazzo del Serraglio, detto anche Villa del Serraglio, è una dimora rinascimentale costruita dalla famiglia Gonzaga come residenza di villeggiatura. Il palazzo è circondato da un giardino storico con piante secolari, fontane e statue. La posizione privilegiata sul lungolago offre una vista aperta sull\'acqua e sulle montagne della sponda veronese.'],
    ],

    'garda' => [
        ['name' => 'Punta San Vigilio', 'excerpt' => 'Promontorio romantico con villa rinascimentale e baia riservata.', 'desc' => 'Punta San Vigilio è considerata uno dei luoghi più romantici e incantevoli dell\'intero Lago di Garda. Il promontorio ospita una villa rinascimentale del XVI secolo progettata da Sanmicheli, un piccolo porto, la chiesetta di San Vigilio e la celebre Baia delle Sirene — una spiaggia a pagamento immersa in un parco di cipressi e ulivi. Qui si respira un\'atmosfera di quiete e bellezza senza tempo.'],
        ['name' => 'Centro Storico e Lungolago', 'excerpt' => 'Vicoli veneziani con palazzo pretorio e porticciolo pittoresco.', 'desc' => 'Il centro storico di Garda conserva l\'impronta della dominazione veneziana nei palazzi con logge e bifore, nei vicoli stretti che si aprono su piazzette nascoste e nel Palazzo dei Capitani con la sua loggia trecentesca. Il lungolago è una passeggiata piacevole tra caffè e ristorantini con vista sull\'acqua e sulla Rocca che sovrasta il paese.'],
        ['name' => 'La Rocca', 'excerpt' => 'Sentiero panoramico tra boschi fino alla cima con vista a 360°.', 'desc' => 'La Rocca di Garda è un promontorio boscoso alto 300 metri che si protende nel lago, offrendo sentieri escursionistici di varia difficoltà. La salita alla cima, attraverso boschi di lecci e macchia mediterranea, richiede circa 45 minuti e regala una vista a 360° sul lago, dai monti del Trentino alla pianura veronese. Sulla sommità si trovano i resti di una fortezza medievale e l\'Eremo dei Camaldolesi.'],
        ['name' => 'Villa Albertini', 'excerpt' => 'Villa storica con parco secolare affacciata sul lago.', 'desc' => 'Villa Albertini è una delle dimore storiche più importanti di Garda, circondata da un parco secolare con piante monumentali affacciato sul lago. La villa fu sede di incontri tra Napoleone III e Vittorio Emanuele II durante le guerre d\'indipendenza. I giardini terrazzati scendono fino all\'acqua e offrono un esempio di giardino romantico all\'inglese tra i più belli del Garda.'],
        ['name' => 'Spiagge', 'excerpt' => 'Calette e spiagge con acque cristalline tra promontori rocciosi.', 'desc' => 'Il territorio di Garda offre diverse spiagge tra le più suggestive della sponda veronese. Dalla spiaggia principale del centro a quelle più selvagge ai piedi della Rocca, fino alla raffinata Baia delle Sirene a Punta San Vigilio. Le acque sono limpide e spesso turchesi, con fondali che alternano sabbia e ciottoli. La cornice di ulivi e cipressi completa un paesaggio da cartolina.'],
    ],

    'torri-del-benaco' => [
        ['name' => 'Castello Scaligero', 'excerpt' => 'Castello con museo etnografico e limonaia storica all\'interno.', 'desc' => 'Il Castello Scaligero di Torri del Benaco, costruito nel XIV secolo, ospita oggi un museo etnografico che racconta la storia della pesca, della navigazione e dell\'olivicoltura sul Lago di Garda. All\'interno delle mura si trova una delle limonaie più antiche del lago, risalente al XVIII secolo, ancora coltivata con piante di limoni. La torre di guardia offre una vista panoramica sul lago e sul porto sottostante.'],
        ['name' => 'Porto e Lungolago', 'excerpt' => 'Porto pittoresco con il traghetto per Toscolano-Maderno.', 'desc' => 'Il porto di Torri del Benaco è uno dei più caratteristici del Lago di Garda. Da qui parte il servizio traghetto per Toscolano-Maderno che collega le due sponde del lago. Il porticciolo è circondato da palazzi storici, ristoranti e botteghe artigiane. La passeggiata lungolago, ombreggiata da platani secolari, offre viste aperte sull\'acqua con la costa bresciana sullo sfondo.'],
        ['name' => 'Chiesa dei Santi Pietro e Paolo', 'excerpt' => 'Parrocchiale settecentesca con opere di Giambettino Cignaroli.', 'desc' => 'La Chiesa dei Santi Pietro e Paolo è la parrocchiale di Torri del Benaco, edificata nel XVIII secolo. L\'interno conserva opere d\'arte di pregio, tra cui dipinti di Giambettino Cignaroli, importante pittore veronese del Settecento. L\'organo storico e gli stucchi barocchi completano un interno di notevole ricchezza decorativa. La chiesa si affaccia sulla piazza principale del paese.'],
        ['name' => 'Centro Storico', 'excerpt' => 'Vicoli medievali con case in pietra e botteghe artigiane.', 'desc' => 'Il centro storico di Torri del Benaco è un borgo medievale ben conservato, con vicoli stretti, case in pietra locale, archi e scalinate che salgono dalla riva del lago. L\'atmosfera è quella di un paese rimasto autentico, dove la vita quotidiana scorre a ritmo lento tra botteghe di prodotti tipici, piccoli caffè e scorci panoramici che si aprono improvvisamente sull\'acqua.'],
        ['name' => 'Sentiero delle Ulivete', 'excerpt' => 'Passeggiata tra gli uliveti storici con vista aperta sul lago.', 'desc' => 'Il Sentiero delle Ulivete è una passeggiata panoramica che si snoda tra gli uliveti terrazzati che circondano Torri del Benaco. Gli ulivi gardesani producono un olio extravergine DOP rinomato e questo sentiero permette di scoprire la tradizione olivicola secolare della zona. Lungo il percorso si incontrano muretti a secco, casolari in pietra e punti panoramici con vista sul lago e sul Monte Baldo.'],
    ],

    ];
}
