<?php
/**
 * Itinerari per zona — mappatura destination slug → percorsi vicini
 *
 * @package Instagarda
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Restituisce un array che mappa ogni slug destinazione ai percorsi nelle vicinanze.
 *
 * @return array
 */
function ig_get_itinerari_zona() {

    $trails = array(
        1  => array(
            'name'       => 'Sentiero del Ponale',
            'slug'       => 'sentiero-del-ponale',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 5.2,
            'hours'      => '2:00',
            'difficulty' => 'facile',
            'desc'       => 'Storico sentiero scavato nella roccia che collega Riva del Garda al lago di Ledro.',
            'tags'       => array( 'panoramico', 'vista-lago', 'consigliato' ),
        ),
        2  => array(
            'name'       => 'Rocca di Manerba',
            'slug'       => 'rocca-di-manerba',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 3.5,
            'hours'      => '1:15',
            'difficulty' => 'facile',
            'desc'       => 'Breve escursione alla rocca panoramica che domina il Golfo di Manerba.',
            'tags'       => array( 'panoramico', 'vista-lago', 'famiglie' ),
        ),
        3  => array(
            'name'       => 'Sentiero dei Limoni',
            'slug'       => 'sentiero-dei-limoni',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 2.8,
            'hours'      => '1:00',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata tra le antiche limonaie terrazzate sul versante occidentale del Garda.',
            'tags'       => array( 'famiglie', 'culturale', 'panoramico' ),
        ),
        4  => array(
            'name'       => 'Cima Comer da Gargnano',
            'slug'       => 'cima-comer-gargnano',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 12.5,
            'hours'      => '5:30',
            'difficulty' => 'difficile',
            'desc'       => 'Salita impegnativa verso la Cima Comer con viste straordinarie sul lago.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        5  => array(
            'name'       => 'Sentiero del Ventrar',
            'slug'       => 'sentiero-del-ventrar',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 7.0,
            'hours'      => '3:00',
            'difficulty' => 'media',
            'desc'       => 'Percorso nel versante orientale del Monte Baldo con panorami sul lago di Garda.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        6  => array(
            'name'       => 'Monte Baldo — Cresta',
            'slug'       => 'monte-baldo-cresta',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 8.5,
            'hours'      => '3:30',
            'difficulty' => 'media',
            'desc'       => 'Traversata lungo la cresta del Monte Baldo con viste a 360° sul Garda e le Alpi.',
            'tags'       => array( 'panoramico', 'vista-lago', 'consigliato' ),
        ),
        7  => array(
            'name'       => 'Punta San Vigilio',
            'slug'       => 'punta-san-vigilio',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 4.0,
            'hours'      => '1:30',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata alla punta più romantica del Garda, con olivi e cipresso.',
            'tags'       => array( 'famiglie', 'panoramico', 'vista-lago' ),
        ),
        9  => array(
            'name'       => 'Eremo di San Giorgio',
            'slug'       => 'eremo-di-san-giorgio',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 3.2,
            'hours'      => '1:15',
            'difficulty' => 'facile',
            'desc'       => 'Sentiero tra vigneti e ulivi fino all\'antico eremo di San Giorgio sul lago.',
            'tags'       => array( 'culturale', 'panoramico', 'famiglie' ),
        ),
        10 => array(
            'name'       => 'Busatte — Tempesta',
            'slug'       => 'busatte-tempesta',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 4.0,
            'hours'      => '1:30',
            'difficulty' => 'facile',
            'desc'       => 'Percorso spettacolare con scalinate sospese sul lago di Torbole.',
            'tags'       => array( 'panoramico', 'vista-lago', 'consigliato' ),
        ),
        11 => array(
            'name'       => 'Monte Brione',
            'slug'       => 'monte-brione',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 5.5,
            'hours'      => '2:00',
            'difficulty' => 'facile',
            'desc'       => 'Anello panoramico sul Monte Brione con viste su Riva del Garda e il lago.',
            'tags'       => array( 'panoramico', 'vista-lago', 'famiglie' ),
        ),
        13 => array(
            'name'       => 'Ciclabile Limone — Riva',
            'slug'       => 'ciclabile-limone-riva',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 15.0,
            'hours'      => '1:00',
            'difficulty' => 'facile',
            'desc'       => 'Pista ciclabile sul lago tra Limone sul Garda e Riva del Garda.',
            'tags'       => array( 'famiglie', 'vista-lago', 'consigliato' ),
        ),
        14 => array(
            'name'       => 'Ciclopista del Mincio',
            'slug'       => 'ciclopista-del-mincio',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 43.0,
            'hours'      => '3:00',
            'difficulty' => 'facile',
            'desc'       => 'Lunga ciclabile pianeggiante da Peschiera del Garda a Mantova lungo il Mincio.',
            'tags'       => array( 'famiglie', 'mezzi', 'consigliato' ),
        ),
        15 => array(
            'name'       => 'Colline Moreniche',
            'slug'       => 'colline-moreniche',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 38.0,
            'hours'      => '2:30',
            'difficulty' => 'media',
            'desc'       => 'Cicloturismo tra le colline moreniche a sud del Garda tra vigneti e borghi.',
            'tags'       => array( 'panoramico', 'culturale' ),
        ),
        16 => array(
            'name'       => 'Ciclabile della Vallagarina',
            'slug'       => 'ciclabile-vallagarina',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 25.0,
            'hours'      => '1:45',
            'difficulty' => 'facile',
            'desc'       => 'Pista ciclabile pianeggiante lungo l\'Adige dalla valle di Rovereto a Riva.',
            'tags'       => array( 'famiglie', 'consigliato' ),
        ),
        17 => array(
            'name'       => 'Tremalzo Trail',
            'slug'       => 'tremalzo-trail',
            'type'       => 'mtb',
            'type_label' => 'MTB',
            'km'         => 32.0,
            'hours'      => '5:00',
            'difficulty' => 'difficile',
            'desc'       => 'Leggendario trail MTB sul Passo Tremalzo, tra i più famosi delle Alpi del Garda.',
            'tags'       => array( 'panoramico', 'consigliato' ),
        ),
        18 => array(
            'name'       => 'Trail 601 Monte Baldo',
            'slug'       => 'trail-601-monte-baldo',
            'type'       => 'mtb',
            'type_label' => 'MTB',
            'km'         => 18.0,
            'hours'      => '3:30',
            'difficulty' => 'difficile',
            'desc'       => 'Discesa tecnica sul versante veronese del Monte Baldo con funivia da Malcesine.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        19 => array(
            'name'       => 'Ponale MTB',
            'slug'       => 'ponale-mtb',
            'type'       => 'mtb',
            'type_label' => 'MTB',
            'km'         => 12.0,
            'hours'      => '2:00',
            'difficulty' => 'media',
            'desc'       => 'Versione MTB del Sentiero del Ponale con variante tecnica sul vecchio tracciato.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        20 => array(
            'name'       => 'San Michele — Monte Cas',
            'slug'       => 'san-michele-monte-cas',
            'type'       => 'mtb',
            'type_label' => 'MTB',
            'km'         => 22.0,
            'hours'      => '3:00',
            'difficulty' => 'media',
            'desc'       => 'Giro MTB tra i boschi della Valtenesi bresciana con viste sul Garda.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        21 => array(
            'name'       => 'Via Ferrata Cima Capi',
            'slug'       => 'via-ferrata-cima-capi',
            'type'       => 'ferrata',
            'type_label' => 'Via Ferrata',
            'km'         => 4.5,
            'hours'      => '4:00',
            'difficulty' => 'difficile',
            'desc'       => 'Via ferrata esposta sulla Cima Capi con panorama spettacolare su Riva del Garda.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        22 => array(
            'name'       => 'Via Ferrata Monte Colodri',
            'slug'       => 'via-ferrata-monte-colodri',
            'type'       => 'ferrata',
            'type_label' => 'Via Ferrata',
            'km'         => 2.5,
            'hours'      => '2:30',
            'difficulty' => 'media',
            'desc'       => 'Via ferrata sul Monte Colodri ad Arco, ideale per avvicinarsi all\'arrampicata.',
            'tags'       => array( 'panoramico' ),
        ),
        24 => array(
            'name'       => 'Windsurf & Kitesurf Torbole',
            'slug'       => 'windsurf-kitesurf-torbole',
            'type'       => 'water',
            'type_label' => 'Acquatici',
            'km'         => 0.0,
            'hours'      => '—',
            'difficulty' => 'media',
            'desc'       => 'Torbole è la capitale europea del windsurf grazie ai venti costanti Pelèr e Ora.',
            'tags'       => array( 'consigliato', 'balneabile' ),
        ),
        25 => array(
            'name'       => 'SUP Tour Sirmione',
            'slug'       => 'sup-tour-sirmione',
            'type'       => 'water',
            'type_label' => 'Acquatici',
            'km'         => 0.0,
            'hours'      => '2:00',
            'difficulty' => 'facile',
            'desc'       => 'Tour in stand-up paddle attorno alla penisola di Sirmione tra grotte e acque cristalline.',
            'tags'       => array( 'famiglie', 'balneabile', 'consigliato' ),
        ),
        26 => array(
            'name'       => 'Vela — Regate del Garda',
            'slug'       => 'vela-regate-del-garda',
            'type'       => 'water',
            'type_label' => 'Acquatici',
            'km'         => 0.0,
            'hours'      => '—',
            'difficulty' => 'media',
            'desc'       => 'Il Garda è uno dei laghi più rinomati al mondo per la vela grazie ai venti regolari.',
            'tags'       => array( 'consigliato' ),
        ),
        27 => array(
            'name'       => 'Canyoning Rio Nero',
            'slug'       => 'canyoning-rio-nero',
            'type'       => 'water',
            'type_label' => 'Acquatici',
            'km'         => 0.0,
            'hours'      => '3:00',
            'difficulty' => 'difficile',
            'desc'       => 'Canyoning nel Rio Nero, vicino a Torbole, tra cascate e salti nell\'acqua gelida.',
            'tags'       => array( 'balneabile' ),
        ),
        28 => array(
            'name'       => 'Punta Larici da Pregasina',
            'slug'       => 'punta-larici-pregasina',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 5.0,
            'hours'      => '2:00',
            'difficulty' => 'media',
            'desc'       => 'Escursione da Pregasina alla Punta Larici, belvedere mozzafiato sopra Riva del Garda.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        29 => array(
            'name'       => 'Sentiero del Sole',
            'slug'       => 'sentiero-del-sole',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 9.0,
            'hours'      => '3:30',
            'difficulty' => 'media',
            'desc'       => 'Percorso panoramico sopra Limone sul Garda con viste sui limoneti e il lago.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        30 => array(
            'name'       => 'Monte Tremalzo e Corno della Marogna',
            'slug'       => 'monte-tremalzo-corno-marogna',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 14.0,
            'hours'      => '5:30',
            'difficulty' => 'difficile',
            'desc'       => 'Lungo anello dal Passo Tremalzo verso le cime più selvagge delle Alpi di Ledro.',
            'tags'       => array( 'panoramico' ),
        ),
        31 => array(
            'name'       => 'Ponte Tibetano di Torri del Benaco',
            'slug'       => 'ponte-tibetano-torri',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 3.0,
            'hours'      => '1:00',
            'difficulty' => 'facile',
            'desc'       => 'Breve percorso che conduce al ponte tibetano sospeso sopra la costa veronese del Garda.',
            'tags'       => array( 'famiglie', 'panoramico', 'consigliato' ),
        ),
        32 => array(
            'name'       => 'Monte Luppia e Petroglifi',
            'slug'       => 'monte-luppia-petroglifi',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 6.0,
            'hours'      => '2:00',
            'difficulty' => 'facile',
            'desc'       => 'Salita al Monte Luppia con visita alle incisioni rupestri preistoriche e vedute sul Garda.',
            'tags'       => array( 'culturale', 'panoramico', 'famiglie' ),
        ),
        37 => array(
            'name'       => 'Sentiero della Salute',
            'slug'       => 'sentiero-della-salute-malcesine',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 8.0,
            'hours'      => '2:30',
            'difficulty' => 'facile',
            'desc'       => 'Anello rilassante tra oliveti e boschi sopra Malcesine con panorami sul lago.',
            'tags'       => array( 'famiglie', 'panoramico', 'vista-lago' ),
        ),
        38 => array(
            'name'       => 'Brenzone Nordic Walking Park',
            'slug'       => 'brenzone-nordic-walking',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 20.0,
            'hours'      => '3:00',
            'difficulty' => 'facile',
            'desc'       => 'Rete di sentieri attrezzati per nordic walking tra i borghi di Brenzone.',
            'tags'       => array( 'famiglie', 'accessibile' ),
        ),
        39 => array(
            'name'       => 'Rocca di Garda & Eremo Camaldolesi',
            'slug'       => 'rocca-di-garda-camaldolesi',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 7.0,
            'hours'      => '2:00',
            'difficulty' => 'facile',
            'desc'       => 'Salita alla Rocca di Garda con visita all\'eremo camaldolese tra cipressi e olivi.',
            'tags'       => array( 'culturale', 'panoramico', 'vista-lago' ),
        ),
        41 => array(
            'name'       => 'Mura UNESCO di Peschiera',
            'slug'       => 'mura-unesco-peschiera',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 3.0,
            'hours'      => '1:00',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata lungo le mura veneziane di Peschiera del Garda, patrimonio UNESCO.',
            'tags'       => array( 'famiglie', 'culturale', 'accessibile', 'consigliato' ),
        ),
        45 => array(
            'name'       => 'Peschiera — Sirmione — Garda',
            'slug'       => 'peschiera-sirmione-desenzano',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 36.0,
            'hours'      => '2:30',
            'difficulty' => 'facile',
            'desc'       => 'Giro del lago tra Peschiera, Sirmione e Garda con borghi e panorami.',
            'tags'       => array( 'famiglie', 'vista-lago', 'consigliato' ),
        ),
        46 => array(
            'name'       => 'Peschiera — Garda Lungolago',
            'slug'       => 'peschiera-garda-lungolago',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 18.0,
            'hours'      => '1:30',
            'difficulty' => 'facile',
            'desc'       => 'Cicloturistica sul lato veronese del basso Garda da Peschiera fino a Garda.',
            'tags'       => array( 'famiglie', 'vista-lago' ),
        ),
        47 => array(
            'name'       => 'Strada del Vino Bardolino',
            'slug'       => 'strada-vino-bardolino',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 35.0,
            'hours'      => '2:30',
            'difficulty' => 'media',
            'desc'       => 'Ciclovia tra vigneti e cantine della Strada del Vino Bardolino sulle colline moreniche.',
            'tags'       => array( 'panoramico', 'culturale', 'ristori' ),
        ),
        49 => array(
            'name'       => 'Salò — Valtenesi Loop',
            'slug'       => 'salo-valtenesi-loop',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 48.0,
            'hours'      => '3:00',
            'difficulty' => 'media',
            'desc'       => 'Giro ciclistico tra Salò e la Valtenesi bresciana tra uliveti e borghi storici.',
            'tags'       => array( 'panoramico', 'ristori' ),
        ),
        50 => array(
            'name'       => 'Ciclopedonale Brenzone — Malcesine',
            'slug'       => 'ciclopedonale-brenzone-malcesine',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 20.0,
            'hours'      => '1:30',
            'difficulty' => 'facile',
            'desc'       => 'Pista ciclopedonale lungo il lago sul versante veronese da Brenzone a Malcesine.',
            'tags'       => array( 'famiglie', 'vista-lago', 'accessibile' ),
        ),
        51 => array(
            'name'       => 'Monte Baldo Red Tour',
            'slug'       => 'monte-baldo-red-tour',
            'type'       => 'mtb',
            'type_label' => 'MTB',
            'km'         => 35.0,
            'hours'      => '4:00',
            'difficulty' => 'difficile',
            'desc'       => 'Giro MTB lungo la cresta del Monte Baldo con ascesa in funivia da Malcesine.',
            'tags'       => array( 'panoramico', 'consigliato' ),
        ),
        54 => array(
            'name'       => 'Via Ferrata delle Taccole',
            'slug'       => 'via-ferrata-delle-taccole',
            'type'       => 'ferrata',
            'type_label' => 'Via Ferrata',
            'km'         => 3.0,
            'hours'      => '6:00',
            'difficulty' => 'difficile',
            'desc'       => 'Via ferrata impegnativa sul Monte Baldo con tratti esposti e panorami su tutto il lago.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        55 => array(
            'name'       => 'Strada della Forra',
            'slug'       => 'strada-della-forra',
            'type'       => 'drive',
            'type_label' => 'Scenic Drive',
            'km'         => 6.0,
            'hours'      => '0:30',
            'difficulty' => 'media',
            'desc'       => 'Strada panoramica scavata nella roccia definita da Churchill "l\'ottava meraviglia del mondo".',
            'tags'       => array( 'panoramico', 'vista-lago', 'consigliato' ),
        ),
        57 => array(
            'name'       => 'Valvestino e Cima Rest',
            'slug'       => 'valvestino-cima-rest',
            'type'       => 'drive',
            'type_label' => 'Scenic Drive',
            'km'         => 30.0,
            'hours'      => '1:00',
            'difficulty' => 'media',
            'desc'       => 'Scenic drive attraverso la Valle di Valvestino fino alle pendici della Cima Rest.',
            'tags'       => array( 'panoramico' ),
        ),
        58 => array(
            'name'       => 'Garda Trek — Top Loop',
            'slug'       => 'garda-trek-top-loop',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 95.0,
            'hours'      => '7 tappe',
            'difficulty' => 'difficile',
            'desc'       => 'Il grande anello alto del Garda Trek che attraversa le cime più spettacolari attorno al lago.',
            'tags'       => array( 'panoramico', 'multiday', 'consigliato' ),
        ),
        59 => array(
            'name'       => 'Garda Trek — Medium Loop',
            'slug'       => 'garda-trek-medium-loop',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 73.0,
            'hours'      => '4 tappe',
            'difficulty' => 'media',
            'desc'       => 'Anello intermedio del Garda Trek tra boschi, balconi panoramici e borghi storici.',
            'tags'       => array( 'panoramico', 'multiday' ),
        ),
        60 => array(
            'name'       => 'Garda Trek — Low Loop',
            'slug'       => 'garda-trek-low-loop',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 33.0,
            'hours'      => '2 tappe',
            'difficulty' => 'facile',
            'desc'       => 'Anello basso del Garda Trek, adatto a famiglie e camminatori non esperti.',
            'tags'       => array( 'famiglie', 'multiday', 'panoramico' ),
        ),
        62 => array(
            'name'       => 'Penisola di Sirmione',
            'slug'       => 'penisola-sirmione-grotte-catullo',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 8.5,
            'hours'      => '2:15',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata attorno alla penisola di Sirmione fino alle Grotte di Catullo.',
            'tags'       => array( 'famiglie', 'vista-lago', 'culturale', 'consigliato', 'accessibile' ),
        ),
        63 => array(
            'name'       => 'Lungolago Desenzano',
            'slug'       => 'lungolago-desenzano',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 4.3,
            'hours'      => '1:05',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata sul lungolago di Desenzano del Garda tra il porto antico e il lido.',
            'tags'       => array( 'famiglie', 'vista-lago', 'accessibile' ),
        ),
        64 => array(
            'name'       => 'Lungolago di Salò',
            'slug'       => 'lungolago-salo',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 2.8,
            'hours'      => '0:45',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata sul lungolago di Salò, tra i più eleganti del Garda bresciano.',
            'tags'       => array( 'famiglie', 'vista-lago', 'accessibile' ),
        ),
        65 => array(
            'name'       => 'Croce di Salò',
            'slug'       => 'croce-di-salo',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 7.4,
            'hours'      => '3:00',
            'difficulty' => 'media',
            'desc'       => 'Escursione alla Croce di Salò con vista panoramica sul golfo e le colline della Valtenesi.',
            'tags'       => array( 'panoramico', 'vista-lago' ),
        ),
        66 => array(
            'name'       => 'Castello di Padenghe e Sant\'Emiliano',
            'slug'       => 'castello-padenghe-santemiliano',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 5.7,
            'hours'      => '2:00',
            'difficulty' => 'media',
            'desc'       => 'Percorso tra il castello medievale di Padenghe e l\'oratorio di Sant\'Emiliano.',
            'tags'       => array( 'culturale', 'panoramico' ),
        ),
        67 => array(
            'name'       => 'Lungolago Moniga — Padenghe',
            'slug'       => 'lungolago-moniga-padenghe',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 7.4,
            'hours'      => '1:50',
            'difficulty' => 'facile',
            'desc'       => 'Passeggiata sul lungolago tra Moniga del Garda e Padenghe tra uliveti e spiagge.',
            'tags'       => array( 'famiglie', 'vista-lago', 'balneabile', 'accessibile' ),
        ),
        68 => array(
            'name'       => 'Anello dei Castelli della Valtenesi',
            'slug'       => 'anello-castelli-valtenesi',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 18.0,
            'hours'      => '5:00',
            'difficulty' => 'media',
            'desc'       => 'Grande anello tra i castelli medievali della Valtenesi bresciana.',
            'tags'       => array( 'culturale', 'panoramico' ),
        ),
        69 => array(
            'name'       => 'Rocca di Lonato e Spia d\'Italia',
            'slug'       => 'rocca-lonato-spia-italia',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 10.2,
            'hours'      => '2:40',
            'difficulty' => 'facile',
            'desc'       => 'Escursione alla Rocca di Lonato e alla torre della Spia d\'Italia con vista sulle Alpi.',
            'tags'       => array( 'culturale', 'panoramico', 'famiglie' ),
        ),
        70 => array(
            'name'       => 'Promontorio di San Fermo',
            'slug'       => 'promontorio-san-fermo',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 3.2,
            'hours'      => '1:00',
            'difficulty' => 'facile',
            'desc'       => 'Breve anello sul promontorio di San Fermo a San Felice del Benaco con viste sul Garda.',
            'tags'       => array( 'famiglie', 'panoramico', 'vista-lago' ),
        ),
        71 => array(
            'name'       => 'Ciclabile Valtenesi — Soiano-Padenghe',
            'slug'       => 'ciclabile-valtenesi-soiano',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 10.4,
            'hours'      => '1:10',
            'difficulty' => 'facile',
            'desc'       => 'Pista ciclabile tra Soiano del Lago e Padenghe sul Garda tra vigneti e colline.',
            'tags'       => array( 'famiglie', 'panoramico' ),
        ),
        72 => array(
            'name'       => 'Polpenazze, Anello dei Vigneti',
            'slug'       => 'polpenazze-anello-vigneti',
            'type'       => 'hiking',
            'type_label' => 'Trekking',
            'km'         => 11.0,
            'hours'      => '3:30',
            'difficulty' => 'media',
            'desc'       => 'Anello tra i vigneti di Polpenazze, nel cuore della DOC Garda Classico.',
            'tags'       => array( 'panoramico', 'culturale', 'ristori' ),
        ),
        73 => array(
            'name'       => 'Ciclovia della Valtenesi',
            'slug'       => 'ciclovia-valtenesi-lonato-salo',
            'type'       => 'cycling',
            'type_label' => 'Ciclismo',
            'km'         => 23.4,
            'hours'      => '2:30',
            'difficulty' => 'media',
            'desc'       => 'Lunga ciclovia tra Lonato del Garda e Salò attraverso la Valtenesi bresciana.',
            'tags'       => array( 'panoramico', 'ristori' ),
        ),
    );

    /**
     * Helper interno per raccogliere i trail per id.
     *
     * @param array $ids
     * @param array $trails
     * @return array
     */
    $pick = function( array $ids ) use ( $trails ) {
        $result = array();
        foreach ( $ids as $id ) {
            if ( isset( $trails[ $id ] ) ) {
                $result[] = $trails[ $id ];
            }
        }
        return $result;
    };

    return array(

        // --- Brescia (basso Garda ovest) ---

        'sirmione'            => $pick( array( 62, 25, 45, 15 ) ),

        'desenzano-del-garda' => $pick( array( 63, 15, 45 ) ),

        'peschiera-del-garda' => $pick( array( 14, 41, 45, 46 ) ),

        'lonato-del-garda'    => $pick( array( 69, 73 ) ),

        'padenghe-sul-garda'  => $pick( array( 66, 67 ) ),

        'moniga-del-garda'    => $pick( array( 67, 68 ) ),

        'manerba-del-garda'   => $pick( array( 2 ) ),

        'san-felice-del-benaco' => $pick( array( 70 ) ),

        'soiano-del-lago'     => $pick( array( 71 ) ),

        'polpenazze-del-garda' => $pick( array( 72 ) ),

        // --- Brescia (alto Garda ovest) ---

        'salo'                => $pick( array( 20, 49, 64, 65 ) ),

        'gardone-riviera'     => $pick( array( 64, 65, 4 ) ),

        'toscolano-maderno'   => $pick( array( 4, 64 ) ),

        'gargnano'            => $pick( array( 4, 26, 57 ) ),

        'limone-sul-garda'    => $pick( array( 3, 13, 17, 29, 30 ) ),

        'tremosine-sul-garda' => $pick( array( 55 ) ),

        // --- Trento ---

        'riva-del-garda'      => $pick( array( 1, 10, 11, 16, 19, 21, 28, 58, 59, 60 ) ),

        'nago-torbole'        => $pick( array( 10, 24, 27 ) ),

        'arco'                => $pick( array( 22 ) ),

        // --- Verona (alto Garda est) ---

        'malcesine'           => $pick( array( 5, 6, 18, 37, 51, 54 ) ),

        'brenzone-sul-garda'  => $pick( array( 38, 50 ) ),

        'torri-del-benaco'    => $pick( array( 31 ) ),

        'garda'               => $pick( array( 7, 32, 39 ) ),

        // --- Verona (basso Garda est) ---

        'bardolino'           => $pick( array( 9, 47, 46 ) ),

        'lazise'              => $pick( array( 46, 47 ) ),

        'castelnuovo-del-garda' => $pick( array( 41, 14, 45, 46 ) ),

        'valeggio-sul-mincio' => $pick( array( 14 ) ),

        // --- Capoluogo (città di riferimento) ---

        'verona'              => array(),
        'brescia'             => array(),
        'trento'              => array(),
        'mantova'             => array(),

    );
}
